import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import NavBar from "../../components/NavBar/NavBar";
import { Providers } from "@/src/providers/Providers";
import { TestProvider } from "@/components/context/TestContext";
import { SimulationTestProvider } from "@/components/context/SimulationTestContext";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-white dark:bg-gray-900 text-black dark:text-white">
        <Providers>
          <TestProvider>
            <SimulationTestProvider>
              <NavBar />
              {children}
            </SimulationTestProvider>
          </TestProvider>
        </Providers>
      </body>
    </html>
  );
}
